--------------------------------------------------------
--  File created - Friday-September-04-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SHOP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTDB"."SHOP_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTDB"."PRODUCT_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SHOPPING_CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTDB"."SHOPPING_CART_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDERING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TESTDB"."ORDERING_SEQ"  MINVALUE 0 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table GOSH_CART
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GOSH_CART" 
   (	"CART_ID" NUMBER, 
	"USER_EMAIL" VARCHAR2(255 BYTE), 
	"PRODUCT_ID" NUMBER, 
	"PRODUCT_QTY" NUMBER, 
	"SUB_TOTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOSH_ORDERS
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GOSH_ORDERS" 
   (	"ORDER_ID" NUMBER, 
	"SHOP_ID" NUMBER, 
	"PRODUCT_ID" NUMBER, 
	"USER_EMAIL" VARCHAR2(255 BYTE), 
	"ORDER_AMT" NUMBER, 
	"ORDER_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOSH_PRODUCT
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GOSH_PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"SHOP_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(255 BYTE), 
	"PRODUCT_DESC" VARCHAR2(255 BYTE), 
	"PRODUCT_PHOTO" VARCHAR2(255 BYTE), 
	"PRODUCT_QTY" NUMBER, 
	"PRODUCT_PRICE" NUMBER, 
	"PRODUCT_SHIP" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOSH_SHOP
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GOSH_SHOP" 
   (	"SHOP_ID" NUMBER, 
	"USER_EMAIL" VARCHAR2(255 BYTE), 
	"SHOP_NAME" VARCHAR2(255 BYTE), 
	"SHOP_PHOTO" VARCHAR2(255 BYTE), 
	"SHOP_DESC" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GOSH_USER
--------------------------------------------------------

  CREATE TABLE "TESTDB"."GOSH_USER" 
   (	"USER_EMAIL" VARCHAR2(255 BYTE), 
	"FULLNAME" VARCHAR2(255 BYTE), 
	"USERNAME" VARCHAR2(255 BYTE), 
	"USER_PASSWORD" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TESTDB.GOSH_CART
SET DEFINE OFF;
REM INSERTING into TESTDB.GOSH_ORDERS
SET DEFINE OFF;
REM INSERTING into TESTDB.GOSH_PRODUCT
SET DEFINE OFF;
REM INSERTING into TESTDB.GOSH_SHOP
SET DEFINE OFF;
REM INSERTING into TESTDB.GOSH_USER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index GOSH_CART_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."GOSH_CART_PK" ON "TESTDB"."GOSH_CART" ("CART_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOSH_ORDERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."GOSH_ORDERS_PK" ON "TESTDB"."GOSH_ORDERS" ("ORDER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOSH_PRODUCT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."GOSH_PRODUCT_PK" ON "TESTDB"."GOSH_PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOSH_SHOP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."GOSH_SHOP_PK" ON "TESTDB"."GOSH_SHOP" ("SHOP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GOSH_USER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TESTDB"."GOSH_USER_PK" ON "TESTDB"."GOSH_USER" ("USER_EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table GOSH_CART
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_CART" ADD CONSTRAINT "GOSH_CART_PK" PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."GOSH_CART" MODIFY ("CART_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOSH_ORDERS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_ORDERS" ADD CONSTRAINT "GOSH_ORDERS_PK" PRIMARY KEY ("ORDER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."GOSH_ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOSH_PRODUCT
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_PRODUCT" ADD CONSTRAINT "GOSH_PRODUCT_PK" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."GOSH_PRODUCT" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOSH_SHOP
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_SHOP" ADD CONSTRAINT "GOSH_SHOP_PK" PRIMARY KEY ("SHOP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."GOSH_SHOP" MODIFY ("SHOP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GOSH_USER
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_USER" ADD CONSTRAINT "GOSH_USER_PK" PRIMARY KEY ("USER_EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TESTDB"."GOSH_USER" MODIFY ("USER_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TESTDB"."GOSH_USER" MODIFY ("USER_EMAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table GOSH_CART
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_CART" ADD CONSTRAINT "PRODUCT_CONSTRAINT" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "TESTDB"."GOSH_PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "TESTDB"."GOSH_CART" ADD CONSTRAINT "USER_CONSTRAINT2" FOREIGN KEY ("USER_EMAIL")
	  REFERENCES "TESTDB"."GOSH_USER" ("USER_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOSH_ORDERS
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_ORDERS" ADD CONSTRAINT "PRODUCT_CONSTRAINT2" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "TESTDB"."GOSH_PRODUCT" ("PRODUCT_ID") ENABLE;
  ALTER TABLE "TESTDB"."GOSH_ORDERS" ADD CONSTRAINT "SHOP_CONSTRAINT2" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "TESTDB"."GOSH_SHOP" ("SHOP_ID") ENABLE;
  ALTER TABLE "TESTDB"."GOSH_ORDERS" ADD CONSTRAINT "USER_CONSTRAINT3" FOREIGN KEY ("USER_EMAIL")
	  REFERENCES "TESTDB"."GOSH_USER" ("USER_EMAIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOSH_PRODUCT
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_PRODUCT" ADD CONSTRAINT "SHOP_CONSTRAINT" FOREIGN KEY ("SHOP_ID")
	  REFERENCES "TESTDB"."GOSH_SHOP" ("SHOP_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GOSH_SHOP
--------------------------------------------------------

  ALTER TABLE "TESTDB"."GOSH_SHOP" ADD CONSTRAINT "USER_CONSTRAINT" FOREIGN KEY ("USER_EMAIL")
	  REFERENCES "TESTDB"."GOSH_USER" ("USER_EMAIL") ENABLE;
